### ISSUE TITLE
按guide安装，运行node app.js报找不到模块

### ISSUE THREAD

**Issue by yifon** [Ebookcoin/ebookcoin#15]
Ebookcoin oueikun$ node app.js
log 2017-11-23 14:18:37 Ebookcoin started: 0.0.0.0:7000 
fatal 2017-11-23 14:18:37 Domain master { message: 'Cannot find module \'ed25519\'',
  stack: 'Error: Cannot find module \'ed25519\'\n    at Function.Module._resolveFilename (module.js:536:15)\n    at Function.Module._load (module.js:466:25)\n    at Module.require (module.js:579:17)\n    at require (internal/module.js:11:18)\n    at Object.<anonymous> (/Users/oueikun/Desktop/blockchain/ebookcoin/logic/transaction.js:2:7)\n    at Module._compile (module.js:635:30)\n    at Object.Module._extensions..js (module.js:646:10)\n    at Module.load (module.js:554:32)\n    at tryModuleLoad (module.js:497:12)\n    at Function.Module._load (module.js:489:3)' }

**Comment by imfly** [comment]
模块没有安装正确，可以手动安装一下：

```
npm install --save ed25519
```
