### ISSUE TITLE
在public目录下执行grunt release 的时候报错，不知道什么原因

### ISSUE THREAD

**Issue by xlweifeng** [Ebookcoin/ebookcoin#17]
Running "browserify:release" (browserify) task
>> Error: Cannot find module '../../../../_is-buffer@1.1.6@is-buffer/index.js' from '/home/kuby/project/ebookcoin/ebookcoin/public/node_modules/_core-util-is@1.0.2@core-util-is/lib'
Warning: Error running grunt-browserify. Use --force to continue.

Aborted due to warnings.
kuby@kuby-virtual-machine:~/project/ebookcoin/ebookcoin/public$

**Comment by imfly** [comment]
运行 `bower install` 了吗，如果运行过，请重新运行，确保相应的包已经安装成功。

**Comment by yexue008** [comment]
运行过bower install了，但还是有这个问题。

**Comment by imfly** [comment]
提示 is-buffer 模块没有安装成功，单独安装它试试。网络因素，这是很常见的！

**Comment by mapleyang** [comment]
我也遇到这个问题，单独安装后还是没有解决这个问题
