### ISSUE TITLE
客户端electron程序在这个项目里？

### ISSUE THREAD

**Issue by npm-ued** [Ebookcoin/ebookcoin#19]
亿书技术选型提到客户端采用electron框架，但在项目中没有看到客户端的代码，感谢

**Comment by imfly** [comment]
是的，新的客户端暂时没有释放出来 😄

**Comment by npm-ued** [comment]
新年快乐@imfly老的客户端是web页面？新的客户端有释放计划么，哈哈

**Comment by npm-ued** [comment]
@imfly  新年快乐 老的客户端是web页面？新的客户端有释放计划么，哈哈
