### ISSUE TITLE
public文件夹下面运行grunt release 报错

### ISSUE THREAD

**Issue by wahwahwinner** [Ebookcoin/ebookcoin#23]
Error: Cannot find module '../../bower_components/file-saver/FileSaver.min.js' from '/home/wahwinner/workspace/ebookcoin/ebookcoin/public/static/js'
Warning: Error running grunt-browserify. Use --force to continue.

**Comment by imfly** [comment]
这是版本问题，需要使用 file-saver 1.2.0 版本，新版本不兼容。

**Comment by wahwahwinner** [comment]
https://github.com/eligrey/FileSaver.js/issues/436
