### ISSUE TITLE
請問下一代的ebookcoin使用語言

### ISSUE THREAD

**Issue by HamiltonWang** [Ebookcoin/ebookcoin#25]
請問下一代的ebookcoin 也會是用node.js 嗎？有可能用 go 嗎？前端用 react.js? 因為ember 實在不是很 popular

**Comment by imfly** [comment]
node.js版本会一直维护下去，新版已经转向ES6，很快会开源，对于ebookcoin这样的项目，node.js非常适合。另外，计算机语言的未来，前后台统一也是一个很好的方向，所以javascript语言任何项目都无法规避。新的版本，前端已经全面转向react.js。

未来，也会考虑实现go语言版本，那也仅仅是为了迎合市场，或者发挥社区力量。

**Comment by HamiltonWang** [comment]
可以開權限看看我可以幫上什麼忙

**Comment by imfly** [comment]
很快的，正在筹备 😄

**Comment by xeoshow** [comment]
前端建议考虑vue，国内研发多
