### ISSUE TITLE
安装完成，无法访问到wallet.html

### ISSUE THREAD

**Issue by jonahzheng** [Ebookcoin/ebookcoin#26]
server.js
`	router.get('/', function (req, res) {
		if (privated.loaded) {
			res.render('wallet.html', {layout: false});
		} else {
			res.render('loading.html');
		}
	});`

访问http:ip:port/ 好像没有执行到这里

**Comment by imfly** [comment]
文档里说了，这个需要把通过使用git的子模块命令，把钱包客户端clone下来，然后编译，就能访问到了。照着文档仔细做一下吧
