### ISSUE TITLE
关于亿书中的几个属性的疑问

### ISSUE THREAD

**Issue by dongluyang** [Ebookcoin/ebookcoin#28]
您好，我购买了Node.js区块链开发。不过书中对一些属性，没有给出详细的解析，比如secondKeypair、secondSignature、u_secondSignature，他们都是干什么的，解决的问题是什么。困扰很久，一直没有找到合理的答案，在这打扰了

**Comment by imfly** [comment]
你好，限于篇幅，书籍确实没有提供太多详细的解释，有的相对简单，像这几个从字面就可以直接了解了， secondKeypair：第二个键值对，也就是二次签名、支付密码所产生的公钥和私钥对；secondSignature：二次签名；u_secondSignature：二次签名的对应数据库存储的字段信息。也就是说，除了最初注册生成地址的那个私钥对，系统还提供了另一个，用来支付确认，安全性更高。希望对你有帮助。
