### ISSUE TITLE
连接服务器的亿书链失败，listen EADDRNOTAVAIL

### ISSUE THREAD

**Issue by CodingCattwo** [Ebookcoin/ebookcoin#29]
本地用Node 4.6.2 运行node app.js -p 7000 -a 134.175.xx.xx

打算连接到服务器的ebook链

可以ping得到的ip地址，但是出现了连接失败情况
报错详情如下
`fatal 2018-11-14 21:34:30 Domain master { message: 'listen EADDRNOTAVAIL 134.175.91.29:7000',
  stack: 'Error: listen EADDRNOTAVAIL 134.175.91.29:7000\n    at Object.exports._errnoException (util.js:911:11)\n    at exports._exceptionWithHostPort (util.js:934:20)\n    at Server._listen2 (net.js:1235:19)\n    at listen (net.js:1284:10)\n    at net.js:1393:9\n    at nextTickCallbackWith3Args (node.js:469:9)\n    at process._tickDomainCallback (node.js:416:17)\n    at Function.Module.runMain (module.js:443:11)\n    at startup (node.js:139:18)\n    at node.js:990:3' }
`

**Comment by imfly** [comment]
这是启动节点服务器的命令，该节点已经运行起来了。访问： http://134.175.91.29:7000/api/blocks
