### ISSUE TITLE
代码中的requester是啥意思，求解答

### ISSUE THREAD

**Issue by huangxingzhao** [Ebookcoin/ebookcoin#30]
![image](https://user-images.githubusercontent.com/46951131/57150616-5a44ed00-6e01-11e9-9207-847575fd5a9a.png)
就是验证中经常看到一个命名中有requester的属性，我是萌新没看出到底是指啥，求解答，谢谢

**Comment by imfly** [comment]
发送方 sender，请求方也是接收方 requester，这个变量名确实不够好。
