### ISSUE TITLE
执行node app.js 报错 

### ISSUE THREAD

**Issue by Demontf** [Ebookcoin/ebookcoin#5]
log 2016-10-28 10:38:05 Ebookcoin started: 0.0.0.0:7000 
fatal 2016-10-28 10:38:05 Domain master { message: 'Module did not self-register.',
  stack: 'Error: Module did not self-register.\n    at Error (native)\n    at Module.load (module.js:355:32)\n    at Function.Module._load (module.js:310:12)\n    at Module.require (module.js:365:17)\n    at require (module.js:384:17)\n    at bindings (/home/demontf/workspace/ebookcoin/node_modules/ed25519/node_modules/bindings/bindings.js:76:44)\n    at Object.<anonymous> (/home/demontf/workspace/ebookcoin/node_modules/ed25519/index.js:1:99)\n    at Module._compile (module.js:460:26)\n    at Object.Module._extensions..js (module.js:478:10)\n    at Module.load (module.js:355:32)' }
## cat /proc/version

Linux version 3.13.0-24-generic (buildd@panlong) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014

**Comment by imfly** [comment]
在你安装模块的过程中，是不是有什么异常，比如个别模块没有安装成功？重新 `npm i` 试试

**Comment by Demontf** [comment]
抱歉，弄好了 我使用sudo node app.js 就可以了 权限问题 谢谢
