### ISSUE TITLE
我的ed25519模块编译失败

### ISSUE THREAD

**Issue by lxlhum** [Ebookcoin/ebookcoin#7]
我的ed25519模块编译失败，请问您的编译环境是什么呀？

windows 7 下的环境 您试过没？

**Comment by lxlhum** [comment]
问题我自己已经解决了…还是因为微软提供的vs2015的c++编译器的问题，更换为vs2013就好了，另外，在linux正常安装。
所以我感觉还是在liunx写代码会更安全一些，win下总出现一些莫名其妙的问题。

**Comment by imfly** [comment]
:+1:

**Comment by gitGksgk** [comment]
同出现问题，要求C:\openssl-win64\lib下有libeay32.lib，下一个建立目录放进去解决的
