### ISSUE TITLE
前端显示空白

### ISSUE THREAD

**Issue by poria-cat** [Ebookcoin/ebookcoin#9]
很奇怪，构建完成之后浏览器会提示错误：
```
TypeError: angular.module(...).info is not a function
```

```
[$injector:modulerr] Failed to instantiate module ebookcoinApp due to:
Error: [$injector:nomod] Module 'ebookcoinApp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
```

由于angular不了解，所以只能看出来是ebookcoinApp没有加载？
真的很懵

**Comment by imfly** [comment]
你好，这个应该与angular的版本有关系。最近，angular更新太快，而且不兼容以往的版本，所以会出现很多兼容性问题。

**Comment by poria-cat** [comment]
angular和其他插件要改到什么版本呢？我用bower卸载了当前angular装了1.2.8的，发现也不行 @imfly

**Comment by poria-cat** [comment]
项目里用到的一些模块比如angular-chart要求的angular最小版本是1.4.x

**Comment by poria-cat** [comment]
看来作者不准备回复了

**Comment by HamiltonWang** [comment]
他有回覆啊⋯⋯

**Comment by poria-cat** [comment]
兼容问题貌似解决不了，npm会默认安装新版angular。如果换成旧版的话，又有兼容问题。。。。。。。。

**Comment by imfly** [comment]
请把https://github.com/Ebookcoin/client/blob/9306d56f6b23c2d5dd31a28667c9a2f6b0d28b2a/package.json
里的对应

```
"angular-resource": "latest",
"angular-route": "latest",
"angular-filter": "latest",
```

所有`latest`都改成`~1.2.8`试试，总之不要使用angular 1.6.4以上的版本

这个问题尝试两遍，应该不难解决。

**Comment by rogerfanrui** [comment]
"angular-resource": "~1.2.8",
    "angular-route": "~1.2.8",
    "angular-filter": "~0.5.16",

**Comment by yowangbin** [comment]
你们的太弱了，项目按文档都跑不起来，这样也可以出书么

**Comment by harunme** [comment]
前端启动都报错，公司为什么有这么重的历史包袱？还在用ng这么低的版本
